# omron_moveit_config/config/joint_limits.yaml

default_velocity_scaling_factor: 0.2
default_acceleration_scaling_factor: 0.2

joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 5.72468      # 328 °/s laut Datenblatt
    has_acceleration_limits: true
    max_acceleration: 3.0
  joint_2:
    has_velocity_limits: true
    max_velocity: 5.23599      # 300 °/s
    has_acceleration_limits: true
    max_acceleration: 3.0
  joint_3:
    has_velocity_limits: true
    max_velocity: 6.54498      # 375 °/s
    has_acceleration_limits: true
    max_acceleration: 4.0
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.54498      # 375 °/s
    has_acceleration_limits: true
    max_acceleration: 6.0
  joint_5:
    has_velocity_limits: true
    max_velocity: 6.54498      # 375 °/s
    has_acceleration_limits: true
    max_acceleration: 6.0
  joint_6:
    has_velocity_limits: true
    max_velocity: 10.47198     # 600 °/s
    has_acceleration_limits: true
    max_acceleration: 8.0
