# omron_moveit_config/config/ompl_planning.yaml
# Minimal-Config für OMPL beim Omron Viper S650

# Welcher Planner-Plugin benutzt wird
planning_plugins:
  - ompl_interface/OMPLPlanner

# Request-Adapter (vor dem eigentlichen Planen)
request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
  - default_planning_request_adapters/CheckForStackedConstraints

# Response-Adapter (nach dem Planen) – hier kommt die Zeitparameterisierung!
response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization

# Toleranz für Bounds-Fehler im Startzustand
start_state_max_bounds_error: 0.1

# Konkrete OMPL-Planner-Konfigurationen
# -> "range" weggelassen, wir nutzen nur die Defaults.
planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect

  RRTkConfigDefault:
    type: geometric::RRT

  RRTstarkConfigDefault:
    type: geometric::RRTstar

# Diese Planner der Arm-Gruppe zuordnen
omron_arm_group:
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTkConfigDefault
    - RRTstarkConfigDefault
