planning_plugins:
  - stomp_moveit/StompPlanner

request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
  - default_planning_request_adapters/CheckForStackedConstraints

response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  # optional:
  # - default_planning_response_adapters/ValidateSolution
  # - default_planning_response_adapters/AddRuckigTrajectorySmoothing

start_state_max_bounds_error: 0.1
