planning_plugins:
  - ompl_interface/OMPLPlanner

ompl:
  default_planner_config: RRTConnectkConfigDefault

request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
  - default_planning_request_adapters/CheckForStackedConstraints

response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  # Optional, falls du später mehr willst:
  # - default_planning_response_adapters/AddRuckigTrajectorySmoothing
  # - default_planning_response_adapters/DisplayMotionPath
  # - default_planning_response_adapters/ValidateSolution

start_state_max_bounds_error: 0.1

planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.1
  RRTkConfigDefault:
    type: geometric::RRT
    range: 0.1
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.1
    # weitere Planner kannst du hier ergänzen
