# omron_moveit_config/config/pilz_industrial_motion_planner_planning.yaml

planning_plugins:
  - pilz_industrial_motion_planner/CommandPlanner

request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision

response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization

start_state_max_bounds_error: 0.1

planner_configs:
  PTP:
    type: pilz_industrial_motion_planner/CommandPlanner
  LIN:
    type: pilz_industrial_motion_planner/CommandPlanner
  CIRC:
    type: pilz_industrial_motion_planner/CommandPlanner
