frames:
  meca:
    tcp: "tcp"
    world: "world"
    robot_mount: "robot_mount"
    home: "home"
    predispense: "predispense"
    service: "service"
    scene: "scene"
    substrate: "substrate"
    substrate_mount: "substrate_mount"
    cage: "cage"
    tool_mount: "tool_mount"