# spraycoater_bringup/config/frames.yaml
version: 1
frames:
  world:           "world"
  robot_mount:     "robot_mount"
  tool_mount:      "tool_mount"
  tcp:             "tcp"

  cage:            "cage"
  substrate_mount: "substrate_mount"
  substrate:       "substrate"
  
  home:            "home"
  service:         "service"