# spraycoater_bringup/config/paths.yaml
# Zentrale Pfaddefinitionen

# Basispfade (optional, nur Doku)
# bringup_share: package://spraycoater_bringup/config

# Bridge-Node (ServoBridge / "servo")
frames_file:       package://spraycoater_bringup/config/frames.yaml
topics_file:       package://spraycoater_bringup/config/topics.yaml
qos_file:          package://spraycoater_bringup/config/qos.yaml

# Embedded MoveIt Servo (separater Node)
servo_yaml: package://spraycoater_bringup/config/servo.yaml