home:
  frame: world
  xyz:
  - -0.25020695478324084
  - 0.6601472297404523
  - 0.313897838247692
  quat_xyzw:
  - 0.002511121428333329
  - 0.004794016452910335
  - -0.008578489852859526
  - -0.9999485592705586
service:
  frame: world
  xyz:
  - -0.25020131914013877
  - 0.6605459601300537
  - 0.31305685052946075
  quat_xyzw:
  - -0.0009174157293644796
  - 0.0015090409110199816
  - -0.0037347850913509455
  - -0.9999914662257022
