home:
  frame: world
  xyz:
  - 0.2936029976211158
  - 0.6624788934526566
  - 0.31393248129434226
  quat_xyzw:
  - -0.0021883579960030003
  - 0.002371682368246867
  - -0.0033182314259139756
  - -0.9999892877187384
service:
  frame: world
  xyz:
  - -0.25020131914013877
  - 0.6605459601300537
  - 0.31305685052946075
  quat_xyzw:
  - -0.0009174157293644796
  - 0.0015090409110199816
  - -0.0037347850913509455
  - -0.9999914662257022
