home:
  frame: world
  xyz:
  - 3.5256145225481816e-10
  - 0.49400000035378144
  - 0.5850000001420863
  quat_xyzw:
  - -1.5999998938552752e-09
  - 1.6025516081191283e-09
  - 2.220446049250313e-16
  - -1.0
service:
  frame: world
  xyz:
  - -0.25020131914013877
  - 0.6605459601300537
  - 0.31305685052946075
  quat_xyzw:
  - -0.0009174157293644796
  - 0.0015090409110199816
  - -0.0037347850913509455
  - -0.9999914662257022
