home:
  frame: world
  xyz:
  - 0.2982870256315633
  - 0.4762193470160548
  - 0.4352551670594123
  quat_xyzw:
  - -0.715154134922985
  - 0.04828469795592348
  - 0.046945190737057926
  - -0.69571495622311
service:
  frame: world
  xyz:
  - -0.30013828967183076
  - 0.4758797639686681
  - 0.5067155177295022
  quat_xyzw:
  - -0.7151799906602212
  - 0.04823393111699047
  - 0.046977740539402055
  - -0.6956897014776487
