home:
  frame: world
  xyz:
  - 8.326672684688674e-17
  - 0.4490000000017814
  - 0.6949999999980863
  quat_xyzw:
  - -1.5999998938552752e-09
  - 1.6025516081191283e-09
  - 2.220446049250313e-16
  - -1.0
service:
  frame: world
  xyz:
  - 8.326672684688674e-17
  - 0.4490000000017814
  - 0.6949999999980863
  quat_xyzw:
  - -1.5999998938552752e-09
  - 1.6025516081191283e-09
  - 2.220446049250313e-16
  - -1.0
