home:
  frame: world
  xyz:
  - 0.2651033537577476
  - 0.49481715523871417
  - 0.1228954076029479
  quat_xyzw:
  - 7.754003033320491e-05
  - 3.4749367884224815e-05
  - -5.330446767415342e-05
  - -0.9999999949693295
service:
  frame: world
  xyz:
  - -0.25020131914013877
  - 0.6605459601300537
  - 0.31305685052946075
  quat_xyzw:
  - -0.0009174157293644796
  - 0.0015090409110199816
  - -0.0037347850913509455
  - -0.9999914662257022
