home:
  frame: world
  xyz:
  - 0.31073530590979714
  - 0.46249046471279065
  - 0.19130743769106834
  quat_xyzw:
  - 0.002177328224091402
  - -7.167211674119403e-06
  - 2.7537244593922597e-05
  - -0.9999976292132576
service:
  frame: world
  xyz:
  - -0.28686445678177946
  - 0.4625272378900884
  - 0.19132058159073417
  quat_xyzw:
  - 0.0021138516639578188
  - -3.098829677278736e-05
  - 3.6032053545909104e-05
  - -0.9999977646837814
