home:
  frame: world
  xyz:
  - 0.3351013905597102
  - 0.6658844372060208
  - 0.1592448816863029
  quat_xyzw:
  - -8.702862551738756e-06
  - 1.2758438833594304e-05
  - 3.3233347326577796e-05
  - -0.9999999993285136
service:
  frame: world
  xyz:
  - -0.25020131914013877
  - 0.6605459601300537
  - 0.31305685052946075
  quat_xyzw:
  - -0.0009174157293644796
  - 0.0015090409110199816
  - -0.0037347850913509455
  - -0.9999914662257022
