profiles:
  default:
    history: KEEP_LAST
    depth: 10
    reliability: RELIABLE
    durability: VOLATILE

  latched:
    history: KEEP_LAST
    depth: 1
    reliability: RELIABLE
    durability: TRANSIENT_LOCAL

  sensor_data:
    history: KEEP_LAST
    depth: 5
    reliability: BEST_EFFORT
    durability: VOLATILE

  scene_collision:
    history: KEEP_LAST
    depth: 50          # nimm >= Anzahl collision objects, z.B. 50
    reliability: RELIABLE
    durability: TRANSIENT_LOCAL
