scene_objects:
- id: cage
  mesh: ../resource/environment/cage_with_panels.stl
  frame: world
  position:
  - 0.0
  - 0.25
  - -0.01
  rpy_deg:
  - 0.0
  - 0.0
  - 0.0
  mesh_offset:
  - 0.0
  - 0.0
  - 0.0
  mesh_rpy:
  - 0.0
  - 0.0
  - 0.0
- id: substrate_mount
  frame: world
  position:
  - 0.0
  - 0.6
  - 0.0
  rpy_deg:
  - 0.0
  - 0.0
  - 0.0
- id: substrate
  mesh: ../resource/substrates/hemisphere_d100_h2mm.stl
  optional: true
  frame: substrate_mount
  position:
  - 0.0
  - 0.0
  - 0.0
  rpy_deg:
  - 0.0
  - 0.0
  - 0.0
  mesh_offset:
  - 0.0
  - 0.0
  - 0.0
  mesh_rpy:
  - 0.0
  - 0.0
  - 0.0
