scene_objects:
- id: cage
  mesh: ../resource/environment/cage_with_panels.stl
  frame: world
  position:
  - 0.0
  - 0.25
  - 0.0
  rpy_deg:
  - 0.0
  - 0.0
  - 0.0
  mesh_offset:
  - 0.0
  - 0.0
  - 0.0
  mesh_rpy:
  - 0.0
  - 0.0
  - 0.0
- id: substrate_mount
  mesh: ../resource/substrate_mounts/circle_d240_h50.stl
  frame: world
  position:
  - 0.0
  - 0.60
  - 0.0
  rpy_deg:
  - 0.0
  - 0.0
  - 0.0
  mesh_offset:
  - 0.0
  - 0.0
  - 0.0
  mesh_rpy:
  - 0.0
  - 0.0
  - 0.0
- id: scene
  mesh: ''
  frame: substrate_mount
  position:
  - 0.0
  - 0.0
  - 0.05
  rpy_deg:
  - 0.0
  - 0.0
  - 0.0
  mesh_offset:
  - 0.0
  - 0.0
  - 0.0
  mesh_rpy:
  - 0.0
  - 0.0
  - 0.0
- id: substrate
  mesh: ../resource/substrates/hemisphere_d100.stl
  optional: true
  frame: scene
  position:
  - 0.0
  - 0.0
  - 0.0
  rpy_deg:
  - 0.0
  - 0.0
  - 0.0
  mesh_offset:
  - 0.0
  - 0.0
  - 0.0
  mesh_rpy:
  - 0.0
  - 0.0
  - 0.0
