version: 1
active_mount: circle_d240_h25
mounts:
  flat_240x240x25:
    description: Standard Flachhalter 240x240mm
    mesh: package://spraycoater_bringup/resource/substrate_mounts/flat_240x240x25.stl
    scene_offset:
      xyz:
      - 0.0
      - 0.0
      - 25.0
      rpy_deg:
      - 0.0
      - 0.0
      - 0.0
  flat_240x240x50:
    description: Standard Flachhalter 240x240mm
    mesh: package://spraycoater_bringup/resource/substrate_mounts/flat_240x240x50.stl
    scene_offset:
      xyz:
      - 0.0
      - 0.0
      - 50.0
      rpy_deg:
      - 0.0
      - 0.0
      - 0.0
  circle_d240_h25:
    description: Rundhalter Ø240mm
    mesh: package://spraycoater_bringup/resource/substrate_mounts/circle_d240_h25.stl
    scene_offset:
      xyz:
      - 0.0
      - 0.0
      - 25.0
      rpy_deg:
      - 0.0
      - 0.0
      - 0.0
  circle_d240_h50:
    description: Rundhalter Ø240mm
    mesh: package://spraycoater_bringup/resource/substrate_mounts/circle_d240_h50.stl
    scene_offset:
      xyz:
      - 0.0
      - 0.0
      - 50.0
      rpy_deg:
      - 0.0
      - 0.0
      - 0.0
  post_d30mm_h100mm:
    description: Post-Holder Ø30 × H100
    mesh: package://spraycoater_bringup/resource/substrate_mounts/post_d30mm_h100mm.stl
    scene_offset:
      xyz:
      - 0.0
      - 0.0
      - 100.0
      rpy_deg:
      - 0.0
      - 0.0
      - 0.0
