version: 1

# Welcher Roboter ist aktiv (Key in robots:)
selected: omron   # meca | omron

robots:
  meca:
    moveit_pkg: mecademic_moveit_config
    backend: meca_sim          # später meca_real möglich
    cage_dirs:
      - resource/environment
    mount_dirs:
      - resource/substrate_mounts
    substrate_dirs:
      - resource/substrates

  omron:
    moveit_pkg: omron_moveit_config
    backend: omron_sim         # für echten Roboter: omron_real
    cage_dirs:
      - resource/environment
    mount_dirs:
      - resource/substrate_mounts
    substrate_dirs:
      - resource/substrates

# world → robot_mount
world_to_robot_mount:
  parent: world
  child: robot_mount
  xyz: [0.0, 0.0, 0.0]
  rpy_deg: [0.0, 0.0, 90.0]
